export const doctors = [
  {
    id: "1",
    name: "Dr. Aminul Islam",
    nameBn: "ডা. আমিনুল ইসলাম",
    specialty: "Cardiology",
    specialtyBn: "হৃদরোগ বিশেষজ্ঞ",
    qualification: "MBBS, MD (Cardiology)",
    experience: "15 years",
    image: "/male-doctor-portrait-professional.png",
    available: ["Sunday", "Tuesday", "Thursday"],
    branch: "Kushtia",
    consultationFee: 800,
    about: "Dr. Aminul Islam is a renowned cardiologist with over 15 years of experience in treating heart diseases.",
  },
  {
    id: "2",
    name: "Dr. Fatima Rahman",
    nameBn: "ডা. ফাতেমা রহমান",
    specialty: "Gynecology",
    specialtyBn: "স্ত্রীরোগ বিশেষজ্ঞ",
    qualification: "MBBS, MS (Gynecology)",
    experience: "12 years",
    image: "/female-doctor-portrait-professional-hijab.jpg",
    available: ["Monday", "Wednesday", "Friday"],
    branch: "Kushtia",
    consultationFee: 700,
    about: "Dr. Fatima Rahman specializes in women's health and obstetric care.",
  },
  {
    id: "3",
    name: "Dr. Kamal Hossain",
    nameBn: "ডা. কামাল হোসেন",
    specialty: "Medicine",
    specialtyBn: "মেডিসিন বিশেষজ্ঞ",
    qualification: "MBBS, FCPS (Medicine)",
    experience: "20 years",
    image: "/senior-male-doctor-portrait.jpg",
    available: ["Saturday", "Monday", "Wednesday"],
    branch: "Jhenaidah",
    consultationFee: 600,
    about: "Dr. Kamal Hossain is a senior physician with expertise in internal medicine.",
  },
  {
    id: "4",
    name: "Dr. Nasreen Akter",
    nameBn: "ডা. নাসরীন আক্তার",
    specialty: "Pediatrics",
    specialtyBn: "শিশু বিশেষজ্ঞ",
    qualification: "MBBS, DCH",
    experience: "10 years",
    image: "/female-doctor-pediatrics-portrait.jpg",
    available: ["Sunday", "Tuesday", "Saturday"],
    branch: "Kushtia",
    consultationFee: 500,
    about: "Dr. Nasreen Akter is dedicated to providing the best care for children.",
  },
  {
    id: "5",
    name: "Dr. Rafiqul Islam",
    nameBn: "ডা. রফিকুল ইসলাম",
    specialty: "Orthopedics",
    specialtyBn: "হাড় বিশেষজ্ঞ",
    qualification: "MBBS, MS (Orthopedics)",
    experience: "18 years",
    image: "/male-orthopedic-doctor-portrait.jpg",
    available: ["Monday", "Thursday", "Saturday"],
    branch: "Jhenaidah",
    consultationFee: 750,
    about: "Dr. Rafiqul Islam specializes in bone and joint treatments.",
  },
  {
    id: "6",
    name: "Dr. Shahana Begum",
    nameBn: "ডা. শাহানা বেগম",
    specialty: "Dermatology",
    specialtyBn: "চর্ম বিশেষজ্ঞ",
    qualification: "MBBS, DDV",
    experience: "8 years",
    image: "/female-dermatologist-portrait.png",
    available: ["Wednesday", "Friday", "Sunday"],
    branch: "Kushtia",
    consultationFee: 600,
    about: "Dr. Shahana Begum treats various skin conditions with modern techniques.",
  },
]

export const departments = [
  {
    id: "1",
    name: "Cardiology",
    nameBn: "হৃদরোগ বিভাগ",
    icon: "Heart",
    description: "Comprehensive heart care including ECG, Echo, stress tests and cardiac consultations.",
    descriptionBn: "ইসিজি, ইকো, স্ট্রেস টেস্ট এবং কার্ডিয়াক পরামর্শ সহ সম্পূর্ণ হার্ট কেয়ার।",
    image: "/cardiology-department-hospital-modern.jpg",
  },
  {
    id: "2",
    name: "Gynecology & Obstetrics",
    nameBn: "স্ত্রীরোগ ও প্রসূতি বিভাগ",
    icon: "Baby",
    description: "Complete women's health services including prenatal care, delivery, and gynecological treatments.",
    descriptionBn: "প্রসবপূর্ব যত্ন, প্রসব এবং স্ত্রীরোগ সংক্রান্ত চিকিৎসা সহ সম্পূর্ণ মহিলা স্বাস্থ্য সেবা।",
    image: "/gynecology-department-hospital.jpg",
  },
  {
    id: "3",
    name: "Pediatrics",
    nameBn: "শিশু বিভাগ",
    icon: "Baby",
    description: "Specialized care for infants, children, and adolescents with experienced pediatricians.",
    descriptionBn: "অভিজ্ঞ শিশু বিশেষজ্ঞদের সাথে শিশু এবং কিশোরদের জন্য বিশেষ যত্ন।",
    image: "/pediatrics-children-hospital.jpg",
  },
  {
    id: "4",
    name: "Orthopedics",
    nameBn: "অর্থোপেডিক্স বিভাগ",
    icon: "Bone",
    description: "Treatment for bone, joint, and muscle conditions including fractures and arthritis.",
    descriptionBn: "হাড়, জয়েন্ট এবং পেশীর সমস্যা যেমন ফ্র্যাকচার এবং আর্থ্রাইটিসের চিকিৎসা।",
    image: "/orthopedics-department-xray.jpg",
  },
  {
    id: "5",
    name: "Dermatology",
    nameBn: "চর্মরোগ বিভাগ",
    icon: "User",
    description: "Diagnosis and treatment of skin, hair, and nail conditions.",
    descriptionBn: "ত্বক, চুল এবং নখের সমস্যার নির্ণয় ও চিকিৎসা।",
    image: "/dermatology-clinic-modern.jpg",
  },
  {
    id: "6",
    name: "Radiology & Imaging",
    nameBn: "রেডিওলজি ও ইমেজিং বিভাগ",
    icon: "Scan",
    description: "Advanced imaging services including X-ray, Ultrasound, CT Scan, and MRI.",
    descriptionBn: "এক্স-রে, আল্ট্রাসাউন্ড, সিটি স্ক্যান এবং এমআরআই সহ উন্নত ইমেজিং সেবা।",
    image: "/radiology-mri-ct-scan.jpg",
  },
  {
    id: "7",
    name: "Pathology",
    nameBn: "প্যাথলজি বিভাগ",
    icon: "TestTube",
    description: "Complete laboratory services for blood tests, urine analysis, and other diagnostic tests.",
    descriptionBn: "রক্ত পরীক্ষা, প্রস্রাব বিশ্লেষণ এবং অন্যান্য ডায়াগনস্টিক পরীক্ষার জন্য সম্পূর্ণ ল্যাবরেটরি সেবা।",
    image: "/pathology-laboratory-tests.jpg",
  },
  {
    id: "8",
    name: "ENT",
    nameBn: "নাক কান গলা বিভাগ",
    icon: "Ear",
    description: "Treatment for ear, nose, and throat conditions by specialized ENT surgeons.",
    descriptionBn: "বিশেষজ্ঞ ইএনটি সার্জনদের দ্বারা কান, নাক এবং গলার সমস্যার চিকিৎসা।",
    image: "/ent-department-hospital.jpg",
  },
]

export const diagnosticTests = [
  {
    id: "1",
    name: "Complete Blood Count (CBC)",
    nameBn: "কমপ্লিট ব্লাড কাউন্ট (সিবিসি)",
    category: "Pathology",
    price: 350,
    description: "Measures different components of blood including red blood cells, white blood cells, and platelets.",
    duration: "2-3 hours",
    preparation: "No special preparation required",
  },
  {
    id: "2",
    name: "Lipid Profile",
    nameBn: "লিপিড প্রোফাইল",
    category: "Pathology",
    price: 800,
    description: "Measures cholesterol levels including HDL, LDL, and triglycerides.",
    duration: "4-5 hours",
    preparation: "12 hours fasting required",
  },
  {
    id: "3",
    name: "Thyroid Function Test",
    nameBn: "থাইরয়েড ফাংশন টেস্ট",
    category: "Pathology",
    price: 1200,
    description: "Measures thyroid hormones T3, T4, and TSH.",
    duration: "24 hours",
    preparation: "No special preparation required",
  },
  {
    id: "4",
    name: "X-Ray Chest",
    nameBn: "এক্স-রে চেস্ট",
    category: "Radiology",
    price: 500,
    description: "Digital X-ray imaging of the chest area.",
    duration: "30 minutes",
    preparation: "Remove metal jewelry",
  },
  {
    id: "5",
    name: "Ultrasound Whole Abdomen",
    nameBn: "আল্ট্রাসাউন্ড পূর্ণ পেট",
    category: "Radiology",
    price: 1500,
    description: "Complete abdominal ultrasound imaging.",
    duration: "45 minutes",
    preparation: "6 hours fasting, full bladder recommended",
  },
  {
    id: "6",
    name: "ECG",
    nameBn: "ইসিজি",
    category: "Cardiology",
    price: 300,
    description: "Electrocardiogram to monitor heart rhythm.",
    duration: "15 minutes",
    preparation: "No special preparation required",
  },
  {
    id: "7",
    name: "Echocardiography",
    nameBn: "ইকোকার্ডিওগ্রাফি",
    category: "Cardiology",
    price: 2500,
    description: "Ultrasound imaging of the heart.",
    duration: "30 minutes",
    preparation: "No special preparation required",
  },
  {
    id: "8",
    name: "CT Scan Brain",
    nameBn: "সিটি স্ক্যান ব্রেইন",
    category: "Radiology",
    price: 4500,
    description: "Computed tomography scan of the brain.",
    duration: "1 hour",
    preparation: "Remove metal accessories, inform about allergies",
  },
]

export const testPackages = [
  {
    id: "1",
    name: "Basic Health Checkup",
    nameBn: "বেসিক হেলথ চেকআপ",
    price: 2500,
    originalPrice: 3500,
    tests: ["CBC", "Blood Sugar", "Lipid Profile", "Urine R/E", "ECG"],
    description: "Essential health screening package for everyone.",
  },
  {
    id: "2",
    name: "Cardiac Health Package",
    nameBn: "কার্ডিয়াক হেলথ প্যাকেজ",
    price: 4500,
    originalPrice: 6000,
    tests: ["ECG", "Echocardiography", "Lipid Profile", "Blood Sugar", "Troponin I"],
    description: "Comprehensive heart health assessment.",
  },
  {
    id: "3",
    name: "Diabetic Care Package",
    nameBn: "ডায়াবেটিক কেয়ার প্যাকেজ",
    price: 3000,
    originalPrice: 4200,
    tests: ["HbA1c", "Blood Sugar (F/PP)", "Lipid Profile", "Kidney Function", "Urine R/E"],
    description: "Complete diabetes monitoring and management.",
  },
  {
    id: "4",
    name: "Women's Health Package",
    nameBn: "মহিলা স্বাস্থ্য প্যাকেজ",
    price: 5500,
    originalPrice: 7500,
    tests: ["CBC", "Thyroid Profile", "USG Pelvis", "Pap Smear", "Vitamin D"],
    description: "Comprehensive health screening for women.",
  },
]

export const branches = [
  {
    id: "1",
    name: "Kushtia Main Branch",
    nameBn: "কুষ্টিয়া প্রধান শাখা",
    address: "123 Hospital Road, Kushtia Sadar, Kushtia-7000",
    addressBn: "১২৩ হাসপাতাল রোড, কুষ্টিয়া সদর, কুষ্টিয়া-৭০০০",
    phone: "+880 1234-567890",
    email: "kushtia@amindiagnostic.com",
    hours: "24/7",
    mapUrl: "https://maps.google.com/?q=23.9012,89.1234",
    image: "/modern-hospital-exterior.png",
    services: ["Emergency", "Pathology", "Radiology", "Cardiology", "All Departments"],
  },
  {
    id: "2",
    name: "Jhenaidah Branch",
    nameBn: "ঝিনাইদহ শাখা",
    address: "45 Medical Center, Jhenaidah Sadar, Jhenaidah-7300",
    addressBn: "৪৫ মেডিকেল সেন্টার, ঝিনাইদহ সদর, ঝিনাইদহ-৭৩০০",
    phone: "+880 1234-567891",
    email: "jhenaidah@amindiagnostic.com",
    hours: "8:00 AM - 10:00 PM",
    mapUrl: "https://maps.google.com/?q=23.5445,89.1810",
    image: "/modern-medical-center.png",
    services: ["Pathology", "Radiology", "General Medicine", "Orthopedics"],
  },
]

export const testimonials = [
  {
    id: "1",
    name: "Rahim Uddin",
    nameBn: "রহিম উদ্দিন",
    rating: 5,
    comment: "Excellent service! The doctors are very professional and caring. I have been coming here for 5 years.",
    commentBn: "চমৎকার সেবা! ডাক্তাররা খুবই পেশাদার এবং যত্নশীল। আমি ৫ বছর ধরে এখানে আসছি।",
    date: "2024-10-15",
  },
  {
    id: "2",
    name: "Salma Begum",
    nameBn: "সালমা বেগম",
    rating: 5,
    comment: "Very clean facility with modern equipment. Reports are delivered on time.",
    commentBn: "আধুনিক যন্ত্রপাতি সহ খুব পরিষ্কার সুবিধা। রিপোর্ট সময়মতো দেওয়া হয়।",
    date: "2024-10-10",
  },
  {
    id: "3",
    name: "Abdul Karim",
    nameBn: "আব্দুল করিম",
    rating: 4,
    comment: "The staff is very helpful and the prices are reasonable. Highly recommended!",
    commentBn: "স্টাফরা খুবই সহায়ক এবং দাম যুক্তিসঙ্গত। অত্যন্ত সুপারিশ করি!",
    date: "2024-09-28",
  },
]

export const blogPosts = [
  {
    id: "1",
    title: "Understanding Heart Health: A Complete Guide",
    titleBn: "হার্টের স্বাস্থ্য বোঝা: একটি সম্পূর্ণ গাইড",
    excerpt:
      "Learn about the importance of maintaining a healthy heart and the steps you can take to prevent cardiovascular diseases.",
    excerptBn: "একটি সুস্থ হৃদয় বজায় রাখার গুরুত্ব এবং কার্ডিওভাসকুলার রোগ প্রতিরোধের জন্য আপনি কী পদক্ষেপ নিতে পারেন সে সম্পর্কে জানুন।",
    image: "/heart-health-medical.jpg",
    category: "Cardiology",
    date: "2024-11-01",
    author: "Dr. Aminul Islam",
  },
  {
    id: "2",
    title: "Diabetes Management: Tips for Better Living",
    titleBn: "ডায়াবেটিস ম্যানেজমেন্ট: ভালো জীবনযাপনের টিপস",
    excerpt: "Practical advice for managing diabetes through diet, exercise, and regular monitoring.",
    excerptBn: "খাদ্য, ব্যায়াম এবং নিয়মিত পর্যবেক্ষণের মাধ্যমে ডায়াবেটিস পরিচালনার জন্য ব্যবহারিক পরামর্শ।",
    image: "/diabetes-health-lifestyle.jpg",
    category: "Medicine",
    date: "2024-10-25",
    author: "Dr. Kamal Hossain",
  },
  {
    id: "3",
    title: "Child Nutrition: Building a Strong Foundation",
    titleBn: "শিশু পুষ্টি: একটি শক্তিশালী ভিত্তি তৈরি",
    excerpt: "Essential nutrition guidelines for children of all ages to ensure healthy growth and development.",
    excerptBn: "সুস্থ বৃদ্ধি এবং বিকাশ নিশ্চিত করতে সব বয়সের শিশুদের জন্য প্রয়োজনীয় পুষ্টি নির্দেশিকা।",
    image: "/child-nutrition-healthy-food.jpg",
    category: "Pediatrics",
    date: "2024-10-18",
    author: "Dr. Nasreen Akter",
  },
]

export const faqs = [
  {
    question: "What are your operating hours?",
    questionBn: "আপনাদের কর্মঘণ্টা কত?",
    answer:
      "Our Kushtia branch operates 24/7 including holidays. The Jhenaidah branch is open from 8:00 AM to 10:00 PM daily.",
    answerBn: "আমাদের কুষ্টিয়া শাখা ছুটির দিন সহ ২৪/৭ কাজ করে। ঝিনাইদহ শাখা প্রতিদিন সকাল ৮:০০টা থেকে রাত ১০:০০টা পর্যন্ত খোলা থাকে।",
  },
  {
    question: "Do I need an appointment for diagnostic tests?",
    questionBn: "ডায়াগনস্টিক টেস্টের জন্য কি অ্যাপয়েন্টমেন্ট প্রয়োজন?",
    answer:
      "Appointments are recommended but not mandatory. Walk-ins are welcome, though there might be waiting times during peak hours.",
    answerBn: "অ্যাপয়েন্টমেন্ট সুপারিশ করা হয় কিন্তু বাধ্যতামূলক নয়। ওয়াক-ইন স্বাগত, যদিও ব্যস্ত সময়ে অপেক্ষার সময় থাকতে পারে।",
  },
  {
    question: "How can I get my test reports?",
    questionBn: "আমি কিভাবে আমার টেস্ট রিপোর্ট পেতে পারি?",
    answer:
      "Reports can be collected from our facility or downloaded from our patient portal. We also offer home delivery for reports.",
    answerBn:
      "রিপোর্ট আমাদের সুবিধা থেকে সংগ্রহ করা যায় বা আমাদের পেশেন্ট পোর্টাল থেকে ডাউনলোড করা যায়। আমরা রিপোর্টের হোম ডেলিভারিও অফার করি।",
  },
  {
    question: "What payment methods do you accept?",
    questionBn: "আপনারা কোন পেমেন্ট পদ্ধতি গ্রহণ করেন?",
    answer:
      "We accept cash, credit/debit cards, and mobile banking (bKash, Nagad, Rocket). Insurance claims are also processed.",
    answerBn: "আমরা নগদ, ক্রেডিট/ডেবিট কার্ড এবং মোবাইল ব্যাংকিং (বিকাশ, নগদ, রকেট) গ্রহণ করি। বীমা দাবিও প্রসেস করা হয়।",
  },
  {
    question: "Do you provide emergency services?",
    questionBn: "আপনারা কি জরুরি সেবা প্রদান করেন?",
    answer: "Yes, our Kushtia main branch provides 24/7 emergency services with ambulance facility available.",
    answerBn: "হ্যাঁ, আমাদের কুষ্টিয়া প্রধান শাখা অ্যাম্বুলেন্স সুবিধা সহ ২৪/৭ জরুরি সেবা প্রদান করে।",
  },
]

export const careers = [
  {
    id: "1",
    title: "Medical Officer",
    titleBn: "মেডিকেল অফিসার",
    department: "General Medicine",
    type: "Full-time",
    location: "Kushtia",
    requirements: ["MBBS from recognized institution", "2+ years experience", "Valid BMDC registration"],
    posted: "2024-11-01",
  },
  {
    id: "2",
    title: "Lab Technician",
    titleBn: "ল্যাব টেকনিশিয়ান",
    department: "Pathology",
    type: "Full-time",
    location: "Jhenaidah",
    requirements: ["Diploma in Medical Technology", "1+ year experience", "Knowledge of modern lab equipment"],
    posted: "2024-10-28",
  },
  {
    id: "3",
    title: "Receptionist",
    titleBn: "রিসেপশনিস্ট",
    department: "Administration",
    type: "Full-time",
    location: "Kushtia",
    requirements: ["Graduate degree", "Good communication skills", "Computer proficiency"],
    posted: "2024-10-25",
  },
]
